service: roam-trails-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 1024 #default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: service/create.main
    events:
      - http:
          path: trails
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: service/get.main
    events:
      - http:
          path: trails/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: service/list.main
    events:
      - http:
          path: trails
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: service/update.main
    events:
      - http:
          path: trails/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: service/delete.main
    events:
      - http:
          path: trails/{id}
          method: delete
          cors: true
          authorizer: aws_iam
